const mongoose = require('mongoose');

/**
 * Task Assignment Model
 * Represents tasks assigned to students based on performance
 */
const taskAssignmentSchema = new mongoose.Schema({
  title: {
    type: String,
    required: [true, 'Task title is required'],
    trim: true,
    maxlength: [200, 'Task title cannot exceed 200 characters']
  },
  description: {
    type: String,
    maxlength: [1000, 'Description cannot exceed 1000 characters']
  },
  taskType: {
    type: String,
    enum: ['MCQ', 'Assignment', 'Practice', 'Reading', 'Video', 'Other'],
    default: 'MCQ'
  },
  
  // Student and Course information
  student: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: [true, 'Student is required']
  },
  course: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Course',
    required: [true, 'Course is required']
  },
  subject: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Subject',
    required: [true, 'Subject is required']
  },
  chapter: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Chapter',
    required: [true, 'Chapter is required']
  },
  
  // Assignment details
  assignedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: [true, 'Assigned by is required']
  },
  assignedDate: {
    type: Date,
    default: Date.now
  },
  dueDate: {
    type: Date,
    required: [true, 'Due date is required']
  },
  
  // For auto-generated tasks
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  generationReason: {
    type: String,
    enum: ['Poor CIA Performance', 'Weak Chapter', 'Manual Assignment', 'Scheduled Practice'],
    default: 'Manual Assignment'
  },
  triggerExam: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'CIAExam'
  },
  
  // Task content - for MCQ tasks
  questions: [{
    questionText: {
      type: String,
      required: true,
      maxlength: [1000, 'Question text cannot exceed 1000 characters']
    },
    options: [{
      optionText: String,
      isCorrect: Boolean
    }],
    correctAnswer: {
      type: Number, // Index of correct option
      min: 0,
      max: 3
    },
    marks: {
      type: Number,
      default: 1
    },
    explanation: {
      type: String,
      maxlength: [500, 'Explanation cannot exceed 500 characters']
    },
    difficulty: {
      type: String,
      enum: ['Easy', 'Medium', 'Hard'],
      default: 'Medium'
    }
  }],
  
  // For non-MCQ tasks
  instructions: {
    type: String,
    maxlength: [2000, 'Instructions cannot exceed 2000 characters']
  },
  resources: [{
    title: String,
    type: {
      type: String,
      enum: ['PDF', 'Video', 'Link', 'Document']
    },
    url: String,
    fileId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'File'
    }
  }],
  
  // Assessment configuration
  totalMarks: {
    type: Number,
    default: 0
  },
  passingMarks: {
    type: Number,
    default: 0
  },
  duration: {
    type: Number, // Duration in minutes (for timed tasks)
    min: [0, 'Duration cannot be negative']
  },
  attemptsAllowed: {
    type: Number,
    default: 1,
    min: [1, 'At least 1 attempt must be allowed']
  },
  
  // Submission tracking
  submissions: [{
    attemptNumber: Number,
    submittedAt: Date,
    timeTaken: Number, // in minutes
    marksObtained: Number,
    percentage: Number,
    answers: [{
      questionIndex: Number,
      selectedAnswer: mongoose.Schema.Types.Mixed,
      isCorrect: Boolean,
      marksAwarded: Number
    }],
    feedback: String
  }],
  
  // Status
  status: {
    type: String,
    enum: ['Assigned', 'In Progress', 'Completed', 'Overdue', 'Cancelled'],
    default: 'Assigned'
  },
  
  // Completion tracking
  startedAt: Date,
  completedAt: Date,
  attemptsUsed: {
    type: Number,
    default: 0
  },
  
  // Best performance
  bestScore: {
    marksObtained: {
      type: Number,
      default: 0
    },
    percentage: {
      type: Number,
      default: 0
    },
    attemptNumber: Number
  },
  
  // Priority
  priority: {
    type: String,
    enum: ['Low', 'Medium', 'High', 'Urgent'],
    default: 'Medium'
  },
  
  // Notifications
  reminderSent: {
    type: Boolean,
    default: false
  },
  lastReminderDate: Date,
  
  // Academic year
  academicYear: {
    type: String,
    match: [/^\d{4}-\d{4}$/, 'Academic year must be in format YYYY-YYYY (e.g., 2024-2025)']
  }
}, {
  timestamps: true,
  toJSON: { virtuals: true },
  toObject: { virtuals: true }
});

// Indexes
taskAssignmentSchema.index({ student: 1, status: 1 });
taskAssignmentSchema.index({ course: 1, chapter: 1 });
taskAssignmentSchema.index({ assignedBy: 1 });
taskAssignmentSchema.index({ dueDate: 1, status: 1 });
taskAssignmentSchema.index({ isAutoGenerated: 1, generationReason: 1 });

// Methods
taskAssignmentSchema.methods.toJSON = function() {
  const task = this.toObject();
  task.id = task._id.toString();
  return task;
};

// Method to submit task
taskAssignmentSchema.methods.submitTask = function(answers, timeTaken) {
  this.attemptsUsed += 1;
  
  // Calculate score for MCQ tasks
  let totalMarks = 0;
  let marksObtained = 0;
  const submissionAnswers = [];
  
  if (this.taskType === 'MCQ') {
    this.questions.forEach((question, index) => {
      const studentAnswer = answers[index];
      const isCorrect = studentAnswer === question.correctAnswer;
      const marksAwarded = isCorrect ? question.marks : 0;
      
      totalMarks += question.marks;
      marksObtained += marksAwarded;
      
      submissionAnswers.push({
        questionIndex: index,
        selectedAnswer: studentAnswer,
        isCorrect,
        marksAwarded
      });
    });
  } else {
    totalMarks = this.totalMarks;
    marksObtained = 0; // Will be evaluated manually
  }
  
  const percentage = totalMarks > 0 ? (marksObtained / totalMarks) * 100 : 0;
  
  // Add submission
  const submission = {
    attemptNumber: this.attemptsUsed,
    submittedAt: new Date(),
    timeTaken,
    marksObtained,
    percentage,
    answers: submissionAnswers
  };
  
  this.submissions.push(submission);
  
  // Update best score
  if (!this.bestScore.percentage || percentage > this.bestScore.percentage) {
    this.bestScore = {
      marksObtained,
      percentage,
      attemptNumber: this.attemptsUsed
    };
  }
  
  // Update status
  if (this.status === 'Assigned') {
    this.status = 'In Progress';
    this.startedAt = new Date();
  }
  
  if (this.attemptsUsed >= this.attemptsAllowed) {
    this.status = 'Completed';
    this.completedAt = new Date();
  }
  
  return this;
};

// Method to check if overdue
taskAssignmentSchema.methods.checkOverdue = function() {
  if (this.status !== 'Completed' && this.status !== 'Cancelled' && new Date() > this.dueDate) {
    this.status = 'Overdue';
    return true;
  }
  return false;
};

// Static method to get tasks by student
taskAssignmentSchema.statics.findByStudent = function(studentId, status = null) {
  const query = { student: studentId };
  if (status) {
    query.status = status;
  }
  
  return this.find(query)
    .populate('course', 'name code')
    .populate('subject', 'name code')
    .populate('chapter', 'title chapterNumber')
    .populate('assignedBy', 'name email')
    .sort({ dueDate: 1, priority: -1 });
};

// Static method to get tasks by faculty
taskAssignmentSchema.statics.findByFaculty = function(facultyId) {
  return this.find({ assignedBy: facultyId })
    .populate('student', 'name email studentId')
    .populate('course', 'name code')
    .populate('chapter', 'title chapterNumber')
    .sort({ assignedDate: -1 });
};

// Static method to get overdue tasks
taskAssignmentSchema.statics.getOverdueTasks = function() {
  return this.find({
    status: { $in: ['Assigned', 'In Progress'] },
    dueDate: { $lt: new Date() }
  })
    .populate('student', 'name email')
    .populate('course', 'name code');
};

// Pre-save middleware to calculate total marks for MCQ tasks
taskAssignmentSchema.pre('save', function(next) {
  if (this.taskType === 'MCQ' && this.questions && this.questions.length > 0) {
    this.totalMarks = this.questions.reduce((sum, q) => sum + (q.marks || 1), 0);
    if (!this.passingMarks) {
      this.passingMarks = Math.ceil(this.totalMarks * 0.4); // 40% passing
    }
  }
  next();
});

const TaskAssignment = mongoose.model('TaskAssignment', taskAssignmentSchema);

module.exports = TaskAssignment;
