const TaskAssignment = require('../models/TaskAssignment');
const User = require('../models/User');
const Course = require('../models/Course');
const Subject = require('../models/Subject');
const Chapter = require('../models/Chapter');
const CIAExam = require('../models/CIAExam');
const StudentPerformance = require('../models/StudentPerformance');
const { validationResult } = require('express-validator');

/**
 * @desc    Create manual task assignment
 * @route   POST /api/tasks
 * @access  Private/Faculty
 */
exports.createTask = async (req, res, next) => {
  try {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({
        success: false,
        errors: errors.array()
      });
    }

    const {
      student,
      course,
      subject,
      chapters,
      title,
      description,
      taskType,
      dueDate,
      priority,
      questions
    } = req.body;

    // Verify student exists
    const studentExists = await User.findById(student);
    if (!studentExists || studentExists.role !== 'Student') {
      return res.status(404).json({
        success: false,
        message: 'Student not found'
      });
    }

    // Verify course exists
    const courseExists = await Course.findById(course);
    if (!courseExists) {
      return res.status(404).json({
        success: false,
        message: 'Course not found'
      });
    }

    // Check permissions
    if (req.user.role === 'Faculty' && courseExists.faculty.toString() !== req.user.id) {
      return res.status(403).json({
        success: false,
        message: 'Not authorized to create tasks for this course'
      });
    }

    // Create task
    const task = await TaskAssignment.create({
      student,
      assignedBy: req.user.id,
      course,
      subject,
      chapters: chapters || [],
      title,
      description,
      taskType,
      generationReason: 'Manual',
      dueDate,
      priority: priority || 'Medium',
      questions: questions || [],
      autoGenerated: false
    });

    // Populate references
    await task.populate([
      { path: 'student', select: 'name rollNumber email' },
      { path: 'assignedBy', select: 'name email' },
      { path: 'course', select: 'name code' },
      { path: 'subject', select: 'name code' },
      { path: 'chapters', select: 'title chapterNumber' }
    ]);

    res.status(201).json({
      success: true,
      message: 'Task created successfully',
      data: task
    });
  } catch (error) {
    console.error('Create task error:', error);
    res.status(500).json({
      success: false,
      message: 'Error creating task',
      error: error.message
    });
  }
};

/**
 * @desc    Auto-generate tasks for weak students (CRITICAL FEATURE)
 * @route   POST /api/tasks/auto-generate
 * @access  Private/Faculty
 */
exports.autoGenerateTasks = async (req, res, next) => {
  try {
    const { course, exam, chapter, threshold } = req.body;

    if (!course) {
      return res.status(400).json({
        success: false,
        message: 'Course ID is required'
      });
    }

    // Verify course exists
    const courseExists = await Course.findById(course).populate('faculty');
    if (!courseExists) {
      return res.status(404).json({
        success: false,
        message: 'Course not found'
      });
    }

    // Check permissions
    if (req.user.role === 'Faculty' && courseExists.faculty._id.toString() !== req.user.id) {
      return res.status(403).json({
        success: false,
        message: 'Not authorized to generate tasks for this course'
      });
    }

    const performanceThreshold = threshold || 50;
    const generatedTasks = [];

    if (exam) {
      // Generate tasks based on exam performance
      const examExists = await CIAExam.findById(exam);
      if (!examExists) {
        return res.status(404).json({
          success: false,
          message: 'Exam not found'
        });
      }

      const ExamMarks = require('../models/ExamMarks');
      const weakStudents = await ExamMarks.getWeakStudentsByChapter(exam, performanceThreshold);

      for (const chapterData of weakStudents) {
        for (const student of chapterData.weakStudents) {
          const task = await TaskAssignment.create({
            student: student.studentId,
            assignedBy: req.user.id,
            course,
            subject: examExists.subject,
            chapters: [chapterData.chapter._id],
            title: `Practice Task - ${chapterData.chapter.title}`,
            description: `Based on your performance in ${examExists.title}, practice questions from this chapter to improve your understanding. Current score: ${student.percentage.toFixed(2)}%`,
            taskType: 'MCQ Practice',
            generationReason: 'Poor CIA Performance',
            triggerExam: exam,
            dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days
            priority: student.percentage < 40 ? 'High' : 'Medium',
            autoGenerated: true
          });

          await task.populate([
            { path: 'student', select: 'name rollNumber email' },
            { path: 'chapters', select: 'title chapterNumber' }
          ]);

          generatedTasks.push(task);
        }
      }
    } else if (chapter) {
      // Generate tasks based on chapter performance
      const chapterExists = await Chapter.findById(chapter);
      if (!chapterExists) {
        return res.status(404).json({
          success: false,
          message: 'Chapter not found'
        });
      }

      const weakStudents = await StudentPerformance.find({
        course,
        'chapterPerformance.chapter': chapter,
        'chapterPerformance.percentage': { $lt: performanceThreshold }
      }).populate('student', 'name rollNumber email');

      for (const performance of weakStudents) {
        const chapterPerf = performance.chapterPerformance.find(
          cp => cp.chapter.toString() === chapter
        );

        const task = await TaskAssignment.create({
          student: performance.student._id,
          assignedBy: req.user.id,
          course,
          subject: performance.subject,
          chapters: [chapter],
          title: `Practice Task - ${chapterExists.title}`,
          description: `Your performance in ${chapterExists.title} needs improvement. Complete this practice task to strengthen your understanding. Current score: ${chapterPerf.percentage.toFixed(2)}%`,
          taskType: 'MCQ Practice',
          generationReason: 'Weak Chapter',
          dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
          priority: chapterPerf.percentage < 40 ? 'High' : 'Medium',
          autoGenerated: true
        });

        await task.populate([
          { path: 'student', select: 'name rollNumber email' },
          { path: 'chapters', select: 'title chapterNumber' }
        ]);

        generatedTasks.push(task);
      }
    } else {
      // Generate tasks for all weak students in course
      const weakStudents = await StudentPerformance.find({
        course,
        overallPerformance: { $lt: performanceThreshold }
      }).populate('student', 'name rollNumber email')
        .populate('weakChapters', 'title chapterNumber');

      for (const performance of weakStudents) {
        if (performance.weakChapters.length > 0) {
          const task = await TaskAssignment.create({
            student: performance.student._id,
            assignedBy: req.user.id,
            course,
            subject: performance.subject,
            chapters: performance.weakChapters.map(c => c._id),
            title: `Practice Task - Overall Improvement`,
            description: `Your overall performance needs improvement. Focus on the weak chapters to improve your understanding. Current score: ${performance.overallPerformance.toFixed(2)}%`,
            taskType: 'MCQ Practice',
            generationReason: 'Weak Chapter',
            dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000), // 14 days
            priority: performance.overallPerformance < 40 ? 'High' : 'Medium',
            autoGenerated: true
          });

          await task.populate([
            { path: 'student', select: 'name rollNumber email' },
            { path: 'chapters', select: 'title chapterNumber' }
          ]);

          generatedTasks.push(task);
        }
      }
    }

    res.status(201).json({
      success: true,
      message: `${generatedTasks.length} tasks generated successfully`,
      count: generatedTasks.length,
      data: generatedTasks
    });
  } catch (error) {
    console.error('Auto-generate tasks error:', error);
    res.status(500).json({
      success: false,
      message: 'Error generating tasks',
      error: error.message
    });
  }
};

/**
 * @desc    Get tasks by student
 * @route   GET /api/tasks/student/:studentId
 * @access  Private
 */
exports.getTasksByStudent = async (req, res, next) => {
  try {
    const { studentId } = req.params;
    const { status, course, priority } = req.query;

    const filter = { student: studentId };
    if (status) filter.status = status;
    if (course) filter.course = course;
    if (priority) filter.priority = priority;

    const tasks = await TaskAssignment.find(filter)
      .populate('assignedBy', 'name email')
      .populate('course', 'name code')
      .populate('subject', 'name code')
      .populate('chapters', 'title chapterNumber')
      .populate('triggerExam', 'title examType')
      .sort({ dueDate: 1, priority: -1 });

    res.status(200).json({
      success: true,
      count: tasks.length,
      data: tasks
    });
  } catch (error) {
    console.error('Get tasks by student error:', error);
    res.status(500).json({
      success: false,
      message: 'Error fetching tasks',
      error: error.message
    });
  }
};

/**
 * @desc    Get tasks by faculty
 * @route   GET /api/tasks/faculty/:facultyId
 * @access  Private/Faculty
 */
exports.getTasksByFaculty = async (req, res, next) => {
  try {
    const { facultyId } = req.params;
    const { status, course, priority } = req.query;

    const filter = { assignedBy: facultyId };
    if (status) filter.status = status;
    if (course) filter.course = course;
    if (priority) filter.priority = priority;

    const tasks = await TaskAssignment.find(filter)
      .populate('student', 'name rollNumber email department')
      .populate('course', 'name code')
      .populate('subject', 'name code')
      .populate('chapters', 'title chapterNumber')
      .populate('triggerExam', 'title examType')
      .sort({ dueDate: 1, priority: -1 });

    res.status(200).json({
      success: true,
      count: tasks.length,
      data: tasks
    });
  } catch (error) {
    console.error('Get tasks by faculty error:', error);
    res.status(500).json({
      success: false,
      message: 'Error fetching tasks',
      error: error.message
    });
  }
};

/**
 * @desc    Get single task
 * @route   GET /api/tasks/:id
 * @access  Private
 */
exports.getTaskById = async (req, res, next) => {
  try {
    const task = await TaskAssignment.findById(req.params.id)
      .populate('student', 'name rollNumber email department')
      .populate('assignedBy', 'name email')
      .populate('course', 'name code')
      .populate('subject', 'name code')
      .populate('chapters', 'title chapterNumber content')
      .populate('triggerExam', 'title examType scheduledDate')
      .populate('attempts.submittedAnswers.question');

    if (!task) {
      return res.status(404).json({
        success: false,
        message: 'Task not found'
      });
    }

    res.status(200).json({
      success: true,
      data: task
    });
  } catch (error) {
    console.error('Get task by ID error:', error);
    res.status(500).json({
      success: false,
      message: 'Error fetching task',
      error: error.message
    });
  }
};

/**
 * @desc    Update task
 * @route   PUT /api/tasks/:id
 * @access  Private/Faculty
 */
exports.updateTask = async (req, res, next) => {
  try {
    let task = await TaskAssignment.findById(req.params.id).populate('course');

    if (!task) {
      return res.status(404).json({
        success: false,
        message: 'Task not found'
      });
    }

    // Check permissions
    if (req.user.role === 'Faculty' && task.course.faculty.toString() !== req.user.id) {
      return res.status(403).json({
        success: false,
        message: 'Not authorized to update this task'
      });
    }

    task = await TaskAssignment.findByIdAndUpdate(
      req.params.id,
      req.body,
      {
        new: true,
        runValidators: true
      }
    ).populate([
      { path: 'student', select: 'name rollNumber email' },
      { path: 'course', select: 'name code' },
      { path: 'subject', select: 'name code' },
      { path: 'chapters', select: 'title chapterNumber' }
    ]);

    res.status(200).json({
      success: true,
      message: 'Task updated successfully',
      data: task
    });
  } catch (error) {
    console.error('Update task error:', error);
    res.status(500).json({
      success: false,
      message: 'Error updating task',
      error: error.message
    });
  }
};

/**
 * @desc    Submit task (student)
 * @route   POST /api/tasks/:id/submit
 * @access  Private/Student
 */
exports.submitTask = async (req, res, next) => {
  try {
    const { answers } = req.body;

    let task = await TaskAssignment.findById(req.params.id);

    if (!task) {
      return res.status(404).json({
        success: false,
        message: 'Task not found'
      });
    }

    // Check if student is authorized
    if (task.student.toString() !== req.user.id) {
      return res.status(403).json({
        success: false,
        message: 'Not authorized to submit this task'
      });
    }

    // Check if already completed
    if (task.status === 'Completed') {
      return res.status(400).json({
        success: false,
        message: 'Task already completed'
      });
    }

    // Submit task using model method
    await task.submitTask(answers);

    await task.populate([
      { path: 'student', select: 'name rollNumber email' },
      { path: 'course', select: 'name code' },
      { path: 'subject', select: 'name code' },
      { path: 'chapters', select: 'title chapterNumber' }
    ]);

    res.status(200).json({
      success: true,
      message: 'Task submitted successfully',
      data: task
    });
  } catch (error) {
    console.error('Submit task error:', error);
    res.status(500).json({
      success: false,
      message: 'Error submitting task',
      error: error.message
    });
  }
};

/**
 * @desc    Delete task
 * @route   DELETE /api/tasks/:id
 * @access  Private/Faculty/Admin
 */
exports.deleteTask = async (req, res, next) => {
  try {
    const task = await TaskAssignment.findById(req.params.id).populate('course');

    if (!task) {
      return res.status(404).json({
        success: false,
        message: 'Task not found'
      });
    }

    // Check permissions
    if (req.user.role === 'Faculty' && task.course.faculty.toString() !== req.user.id) {
      return res.status(403).json({
        success: false,
        message: 'Not authorized to delete this task'
      });
    }

    await task.deleteOne();

    res.status(200).json({
      success: true,
      message: 'Task deleted successfully',
      data: {}
    });
  } catch (error) {
    console.error('Delete task error:', error);
    res.status(500).json({
      success: false,
      message: 'Error deleting task',
      error: error.message
    });
  }
};

/**
 * @desc    Get task statistics
 * @route   GET /api/tasks/course/:courseId/statistics
 * @access  Private/Faculty
 */
exports.getTaskStatistics = async (req, res, next) => {
  try {
    const { courseId } = req.params;

    const course = await Course.findById(courseId);
    if (!course) {
      return res.status(404).json({
        success: false,
        message: 'Course not found'
      });
    }

    // Check permissions
    if (req.user.role === 'Faculty' && course.faculty.toString() !== req.user.id) {
      return res.status(403).json({
        success: false,
        message: 'Not authorized to view statistics for this course'
      });
    }

    const statistics = await TaskAssignment.aggregate([
      { $match: { course: course._id } },
      {
        $group: {
          _id: null,
          total: { $sum: 1 },
          assigned: { $sum: { $cond: [{ $eq: ['$status', 'Assigned'] }, 1, 0] } },
          inProgress: { $sum: { $cond: [{ $eq: ['$status', 'In Progress'] }, 1, 0] } },
          completed: { $sum: { $cond: [{ $eq: ['$status', 'Completed'] }, 1, 0] } },
          overdue: { $sum: { $cond: [{ $eq: ['$status', 'Overdue'] }, 1, 0] } },
          autoGenerated: { $sum: { $cond: ['$autoGenerated', 1, 0] } },
          manual: { $sum: { $cond: [{ $not: '$autoGenerated' }, 1, 0] } },
          avgScore: { $avg: '$bestScore' }
        }
      }
    ]);

    const stats = statistics.length > 0 ? statistics[0] : {
      total: 0,
      assigned: 0,
      inProgress: 0,
      completed: 0,
      overdue: 0,
      autoGenerated: 0,
      manual: 0,
      avgScore: 0
    };

    res.status(200).json({
      success: true,
      data: {
        course: {
          id: course._id,
          name: course.name,
          code: course.code
        },
        statistics: {
          total: stats.total,
          byStatus: {
            assigned: stats.assigned,
            inProgress: stats.inProgress,
            completed: stats.completed,
            overdue: stats.overdue
          },
          byType: {
            autoGenerated: stats.autoGenerated,
            manual: stats.manual
          },
          averageScore: Math.round(stats.avgScore * 100) / 100
        }
      }
    });
  } catch (error) {
    console.error('Get task statistics error:', error);
    res.status(500).json({
      success: false,
      message: 'Error fetching task statistics',
      error: error.message
    });
  }
};

/**
 * @desc    Get overdue tasks
 * @route   GET /api/tasks/course/:courseId/overdue
 * @access  Private/Faculty
 */
exports.getOverdueTasks = async (req, res, next) => {
  try {
    const { courseId } = req.params;

    const course = await Course.findById(courseId);
    if (!course) {
      return res.status(404).json({
        success: false,
        message: 'Course not found'
      });
    }

    // Check permissions
    if (req.user.role === 'Faculty' && course.faculty.toString() !== req.user.id) {
      return res.status(403).json({
        success: false,
        message: 'Not authorized to view tasks for this course'
      });
    }

    const overdueTasks = await TaskAssignment.find({
      course: courseId,
      dueDate: { $lt: new Date() },
      status: { $ne: 'Completed' }
    })
      .populate('student', 'name rollNumber email department')
      .populate('chapters', 'title chapterNumber')
      .sort({ dueDate: 1 });

    res.status(200).json({
      success: true,
      count: overdueTasks.length,
      data: overdueTasks
    });
  } catch (error) {
    console.error('Get overdue tasks error:', error);
    res.status(500).json({
      success: false,
      message: 'Error fetching overdue tasks',
      error: error.message
    });
  }
};

module.exports = exports;
